import { jsPDF } from "jspdf";
import type { Baptism } from "../types/baptism.types";
import churchLogo from "../assets/images/church.png"

export const generateBaptismCertificate = (data: Baptism, churchName: string) => {
    const doc = new jsPDF();

    // certifiate Border
    doc.setLineWidth(0.5);
    doc.rect(5, 5, 200, 285);

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(26);
    doc.text("Certificate of Baptism", 105, 20, { align: "center" });

    //logo
    doc.addImage(churchLogo, "PNG", 80, 200, 50, 50);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(14);
    doc.text("This is to certify that", 105, 35, { align: "center" });

    // baptised person's/child's Name
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(data.childName, 105, 50, { align: "center" });

    // certificate Body
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text(
        `was baptized in the name of the Father, and the Son, and of the Holy Spirit on the ${new Date(data.dateOfBaptism).toDateString()} at 
        ${churchName} `, 105, 70, { align: "center" }
    );

    doc.text(`Parents - ${data.nameOfFather} & ${data.nameOfMother}`, 105, 90, { align: "center" });

    doc.text(`Godparents: ${data.nameOfGodFather} & ${data.nameOfGodMother}`,
        105, 105, { align: "center" }
    );

    doc.text(`Place of Birth : ${data.placeOfBirth}`, 105, 120, { align: "center" });
    doc.text(`Current Address : ${data.currentAddress}`, 105, 135, { align: "center" });

    // certificate Footer
    doc.setFontSize(10);
    doc.text("Generated by ©iChurch", 105, 280, {
        align: "center",
    });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);

    // priest's Signature line
    doc.line(72, 170, 135, 170);
    doc.text("Priest's Signature", 105, 178, { align: "center" });

    // saving name
    doc.save(`${data.childName}_Baptism_Certificate.pdf`);
};