import { jsPDF } from "jspdf";
import churchLogo from "../assets/images/church.png"
import heartsImage from "../assets/images/hearts.jpg"
import type { Marriage } from "../types/marriage.types";

export const generateMarriageCertificate = (data: Marriage, churchName: string) => {
    const doc = new jsPDF();

    // certifiate Border
    doc.setLineWidth(0.5);
    doc.rect(5, 5, 200, 285);

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(26);
    doc.text("Certificate of Marriage", 105, 20, { align: "center" });

    //logo
    doc.addImage(churchLogo, "PNG", 80, 200, 50, 50);

    //hearts image
    doc.addImage(heartsImage, "JPG", 100, 54, 10, 10);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(14);
    doc.text("hereby presents this to", 105, 35, { align: "center" });

    // couple's full Names with initials
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(`${data.nameOfBride} & ${data.nameOfGroom}`, 105, 50, { align: "center" });

    // certificate Body
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text(
        `were united in the Holy sacrement of Marriage on this day, ${new Date(data.dateOfMarriage).toDateString()} at 
        ${churchName}. `, 105, 70, { align: "center" }
    );

    doc.text(`As you step into the sacred matrimony, may your journey together be filled with love
        trustworthy, understanding, and happiness. And this magical bond between you grow only strong 
        by the day for in your hearts and surely know that 
        true love lasts forever.`,
        105, 90, { align: "center" }
    );

    doc.text(`Wishing you a lifetime of love and happiness`, 105, 120, { align: "center" });
    doc.text(`to`, 105, 127, { align: "center" });

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(`${data.shortenedCoupleName}`, 105, 135, { align: "center" });
    doc.setFont("helvetica", "normal");

    // certificate Footer
    doc.setFontSize(10);
    doc.text("Generated by ©iChurch", 105, 280, {
        align: "center",
    });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);

    // priest's Signature line
    doc.line(72, 170, 135, 170);
    doc.text("Priest's Signature", 105, 178, { align: "center" });

    // saving name
    doc.save(`${data.shortenedCoupleName}_Marriage_Certificate.pdf`);

};

